//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shibbToADFS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"MIID6jCCAtKgAwIBAgIJANITq5P0ezzOMA0GCSqGSIb3DQEBCwUAMIGJMQswCQYD
VQQGEwJBVDEPMA0GA1UECgwGQUNPbmV0MSMwIQYDVQQLDBpBQ09uZXQgSWRlbnRp
dHkgRmVkZXJhdGlvbjEmMCQGA1UEAwwdZWR1SUQuYXQgTWV0YWRhdGEgU2lnbmlu
ZyBLZXkxHDAaBgkqhkiG9w0BCQEWDWVkdWlkQGFjby5uZXQwHhcNMTgwNDExMTIw
MDA2WhcNMzcxMjMxMTIwMDA2WjCBiTELMAkGA1UEBhMCQVQxDzANBgNVBAoMBkFD
T25ldDEjMCEGA1UECwwaQUNPbmV0IElkZW50aXR5IEZlZGVyYXRpb24xJjAkBgNV
BAMMHWVkdUlELmF0IE1ldGFkYXRhIFNpZ25pbmcgS2V5MRwwGgYJKoZIhvcNAQkB
Fg1lZHVpZEBhY28ubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
wSDLS25Y5spmrB8fykSqzXbTaEssR/cD12foFIDoLwN5PUEwXWWPsl8zXyoFw2nW
lrORK47Z8wjU1QlO4BcZRt8ix52GJXs9Q5xgBs4zE/Xp6hgUBa0if2PxOWoA2UTq
UgBj8L6joVkz5rBeiY7J2CkfvRw+QSzkMm+YEsmAcwpyghavKfDvYSOxubuYBacq
kwGa0J8AkDuiG3kfpydrCE5R8KTt8P65Xie5+g8YCU0mql1vCzD0O48y5dK5SHD4
PhkpG2BAayGiNUR7bDSkVElb3uybwjb0BQI+q0hu4NqpeZjTY0pTnu5oZhQW49e4
M+gKJEoSUceI3CSZ6nSfHwIDAQABo1MwUTAdBgNVHQ4EFgQUTA74FlziE6v2OKUH
HM4n/i8u8uMwHwYDVR0jBBgwFoAUTA74FlziE6v2OKUHHM4n/i8u8uMwDwYDVR0T
AQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAGaJ65BAAKb8B4gxSWF2tkkFZ
7ThEftd8pdp7wTdGOb6uR1fh5wnyHs/TZeM7vJHAmqaobekFpFX0LOnDXAQ9k4kI
O+qYYNJas0YcC9n1R/ZZWkPkJpOnbzArBZq5w6gafLLEiK+nc0GX0swyPbsCL+jh
kYMi38ea4xFpzlIvvharYhr+K9X2P2um6Js/YYuB9i4lzRss5JinVIQyc3OY7u62
zqkUDQ/3Ggu2j+GPF/Ij7+jwIuxXuOB3XpvC8zxSQ/unozRTNY3TR7kvcIxyMA9I
Mo0l1Bhktwu7txYDxCUWXmhqakzLIu9OAL+vpdek1QPp4rKST0NMwMK+kETNJQ==
")]
        public string SigningCert {
            get {
                return ((string)(this["SigningCert"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eduid.at/md/aconet-registered.xml")]
        public string metadataUrl {
            get {
                return ((string)(this["metadataUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""UTF-8""?>
<md:EntitiesDescriptor xmlns:md=""urn:oasis:names:tc:SAML:2.0:metadata"" xmlns:xrd=""http://docs.oasis-open.org/ns/xri/xrd-1.0"" xmlns:mdattr=""urn:oasis:names:tc:SAML:metadata:attribute"" xmlns:shibmd=""urn:mace:shibboleth:metadata:1.0"" xmlns:mdui=""urn:oasis:names:tc:SAML:metadata:ui"" xmlns:saml=""urn:oasis:names:tc:SAML:2.0:assertion"" xmlns:ds=""http://www.w3.org/2000/09/xmldsig#"" xmlns:mdrpi=""urn:oasis:names:tc:SAML:metadata:rpi""/>")]
        public string ADFSMetaData {
            get {
                return ((string)(this["ADFSMetaData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int CacheTimeMinutes {
            get {
                return ((int)(this["CacheTimeMinutes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>//md:SPSSODescriptor</string>\r\n  <string>//md:AttributeAuthorityDescriptor" +
            "</string>\r\n  <string>/md:EntitiesDescriptor/md:EntityDescriptor/md:IDPSSODescrip" +
            "tor/md:SingleSignOnService[@Binding=\"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-P" +
            "OST-SimpleSign\"]</string>\r\n  <string>/md:EntitiesDescriptor/md:EntityDescriptor/" +
            "md:IDPSSODescriptor/md:SingleSignOnService[@Binding=\"urn:oasis:names:tc:SAML:2.0" +
            ":bindings:HTTP-Artifact\"]</string>\r\n  <string>/md:EntitiesDescriptor/md:EntityDe" +
            "scriptor/md:IDPSSODescriptor/md:SingleSignOnService[@Binding=\"urn:oasis:names:tc" +
            ":SAML:2.0:bindings:PAOS\"]</string>\r\n  <string>/md:EntitiesDescriptor/md:EntityDe" +
            "scriptor/md:IDPSSODescriptor/md:SingleSignOnService[@Binding=\"urn:oasis:names:tc" +
            ":SAML:2.0:bindings:SOAP\"]</string>\r\n  <string>/md:EntitiesDescriptor/md:EntityDe" +
            "scriptor/md:IDPSSODescriptor/md:SingleSignOnService[@Binding=\"urn:oasis:names:tc" +
            ":SAML:1.0:bindings:SOAP-binding\"]</string>\r\n  <string>/md:EntitiesDescriptor/md:" +
            "EntityDescriptor/md:IDPSSODescriptor/md:SingleSignOnService[@Binding=\"urn:mace:s" +
            "hibboleth:1.0:profiles:AuthnRequest\"]</string>\r\n  <string>/md:EntitiesDescriptor" +
            "/md:EntityDescriptor/md:IDPSSODescriptor/md:ArtifactResolutionService[@Binding=\"" +
            "urn:oasis:names:tc:SAML:1.0:bindings:SOAP-binding\"]</string>\r\n  <string>/md:Enti" +
            "tiesDescriptor/md:EntityDescriptor/md:IDPSSODescriptor/md:SingleLogoutService[@B" +
            "inding=\"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign\"]</string>\r\n  " +
            "<string>/md:EntitiesDescriptor/md:EntityDescriptor/md:IDPSSODescriptor/md:Single" +
            "LogoutService[@Binding=\"urn:oasis:names:tc:SAML:2.0:bindings:SOAP\"]</string>\r\n</" +
            "ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IdpNodes2Delete {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IdpNodes2Delete"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>//md:IDPSSODescriptor</string>
  <string>//md:AttributeAuthorityDescriptor</string>
  <string>/md:EntitiesDescriptor/md:EntityDescriptor/md:SPSSODescriptor/md:AssertionConsumerService[@Binding=""urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign""]</string>
  <string>/md:EntitiesDescriptor/md:EntityDescriptor/md:SPSSODescriptor/md:AssertionConsumerService[@Binding=""urn:oasis:names:tc:SAML:2.0:bindings:PAOS""]</string>
  <string>/md:EntitiesDescriptor/md:EntityDescriptor/md:SPSSODescriptor/md:SingleLogoutService[@Binding=""urn:oasis:names:tc:SAML:2.0:bindings:SOAP""]</string>
  <string>/md:EntitiesDescriptor/md:EntityDescriptor/md:SPSSODescriptor/md:SingleLogoutService[@Binding=""urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact""]</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SpNodes2Delete {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SpNodes2Delete"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/md:EntitiesDescriptor/md:EntityDescriptor[@entityID=\"{0}\"]")]
        public string XPath2Copy {
            get {
                return ((string)(this["XPath2Copy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>//md:IDPSSODescriptor</string>
  <string>//md:AttributeAuthorityDescriptor</string>
  <string>/md:EntityDescriptor/md:SPSSODescriptor/md:AssertionConsumerService[@Binding=""urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign""]</string>
  <string>/md:EntityDescriptor/md:SPSSODescriptor/md:AssertionConsumerService[@Binding=""urn:oasis:names:tc:SAML:2.0:bindings:PAOS""]</string>
  <string>/md:EntityDescriptor/md:SPSSODescriptor/md:SingleLogoutService[@Binding=""urn:oasis:names:tc:SAML:2.0:bindings:SOAP""]</string>
  <string>/md:EntityDescriptor/md:SPSSODescriptor/md:SingleLogoutService[@Binding=""urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact""]</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SpProxyNodes2Delete {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SpProxyNodes2Delete"]));
            }
        }
    }
}
